import { neon } from '@neondatabase/serverless'

let client
let schemaPromise

const parseDotnetConnectionString = (value) => {
  const entries = Object.fromEntries(
    String(value || '')
      .split(';')
      .map((part) => part.trim())
      .filter(Boolean)
      .map((part) => {
        const separator = part.indexOf('=')
        return separator < 0
          ? [part.toLowerCase(), '']
          : [part.slice(0, separator).trim().toLowerCase(), part.slice(separator + 1).trim()]
      }),
  )

  const host = entries.host || entries.server
  const database = entries.database || entries['initial catalog']
  const username = entries.username || entries['user id'] || entries.user
  const password = entries.password
  if (!host || !database || !username || !password) return ''

  const port = entries.port ? `:${entries.port}` : ''
  return `postgresql://${encodeURIComponent(username)}:${encodeURIComponent(password)}@${host}${port}/${encodeURIComponent(database)}?sslmode=require`
}

export const getDatabaseUrl = () => {
  const direct = process.env.DATABASE_URL || process.env.NEON_DATABASE_URL
  if (direct?.startsWith('postgres')) return direct

  const dotnet = process.env.CONNECTIONSTRINGS__OPMWIKI || process.env.ConnectionStrings__OpmWiki
  return parseDotnetConnectionString(dotnet)
}

export const getSql = () => {
  if (client) return client
  const connectionString = getDatabaseUrl()
  if (!connectionString) {
    throw new Error('DATABASE_URL is not configured.')
  }
  client = neon(connectionString)
  return client
}

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS user_accounts (
    "Id" uuid PRIMARY KEY,
    "Username" varchar(30) NOT NULL,
    "NormalizedUsername" varchar(30) NOT NULL,
    "DisplayName" varchar(60) NOT NULL,
    "PasswordHash" varchar(500) NOT NULL,
    "Role" varchar(20) NOT NULL DEFAULT 'User',
    "Balance" numeric(18,2) NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_accounts_NormalizedUsername"
    ON user_accounts ("NormalizedUsername")`,
  `CREATE INDEX IF NOT EXISTS "IX_user_accounts_Role"
    ON user_accounts ("Role")`,
  `CREATE TABLE IF NOT EXISTS event_comments (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventId" varchar(100) NOT NULL,
    "UserId" uuid NOT NULL REFERENCES user_accounts("Id") ON DELETE RESTRICT,
    "Content" varchar(1000) NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedById" uuid NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS "IX_event_comments_EventId_CreatedAt"
    ON event_comments ("EventId", "CreatedAt")`,
  `CREATE TABLE IF NOT EXISTS forum_topics (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES user_accounts("Id") ON DELETE RESTRICT,
    "Title" varchar(160) NOT NULL,
    "Content" varchar(5000) NOT NULL,
    "IsLocked" boolean NOT NULL DEFAULT false,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS "IX_forum_topics_UpdatedAt"
    ON forum_topics ("UpdatedAt")`,
  `CREATE TABLE IF NOT EXISTS forum_posts (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TopicId" bigint NOT NULL REFERENCES forum_topics("Id") ON DELETE CASCADE,
    "UserId" uuid NOT NULL REFERENCES user_accounts("Id") ON DELETE RESTRICT,
    "Content" varchar(3000) NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "DeletedById" uuid NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS "IX_forum_posts_TopicId_CreatedAt"
    ON forum_posts ("TopicId", "CreatedAt")`,
  `CREATE TABLE IF NOT EXISTS top_up_requests (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES user_accounts("Id") ON DELETE RESTRICT,
    "Provider" varchar(60) NOT NULL,
    "ReferenceCode" varchar(120) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Status" varchar(20) NOT NULL DEFAULT 'Pending',
    "StaffNote" varchar(500) NOT NULL DEFAULT '',
    "ReviewedById" uuid NULL REFERENCES user_accounts("Id") ON DELETE RESTRICT,
    "ReviewedAt" timestamptz NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "IX_top_up_requests_UserId_ReferenceCode"
    ON top_up_requests ("UserId", "ReferenceCode")`,
  `CREATE INDEX IF NOT EXISTS "IX_top_up_requests_Status_CreatedAt"
    ON top_up_requests ("Status", "CreatedAt")`,
]

export const ensureCommunitySchema = async () => {
  if (schemaPromise) return schemaPromise
  schemaPromise = (async () => {
    const sql = getSql()
    for (const statement of schemaStatements) {
      await sql.query(statement)
    }
  })().catch((error) => {
    schemaPromise = undefined
    throw error
  })
  return schemaPromise
}

export const _resetDatabaseForTests = () => {
  client = undefined
  schemaPromise = undefined
}

