// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpmWiki.Infrastructure.Persistence;

#nullable disable

namespace OpmWiki.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpmWikiDbContext))]
    partial class OpmWikiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpmWiki.Domain.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("BioEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BioVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BondListEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BondListVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DuyenEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DuyenVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactionEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FactionVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KeepsakeIcon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("ReleaseChina")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReleaseSea")
                        .HasColumnType("date");

                    b.PrimitiveCollection<string[]>("RolesEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("RolesVi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.PrimitiveCollection<string[]>("TraitsEn")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("TraitsVi")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TypeEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NameEn");

                    b.HasIndex("NameVi");

                    b.HasIndex("Tier", "FactionVi", "TypeVi");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.CharacterEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TermEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TermVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SortOrder")
                        .IsUnique();

                    b.ToTable("character_effects", (string)null);
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnimationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KeepsakeIconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TypeEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SortOrder")
                        .IsUnique();

                    b.ToTable("character_skills", (string)null);
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.GameEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("DetailImages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SectionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TitleVi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.Character", b =>
                {
                    b.OwnsOne("OpmWiki.Domain.Entities.CharacterStats", "BaseStats", b1 =>
                        {
                            b1.Property<string>("CharacterId")
                                .HasColumnType("character varying(80)");

                            b1.Property<int>("Atk")
                                .HasColumnType("integer")
                                .HasColumnName("base_atk");

                            b1.Property<int>("Def")
                                .HasColumnType("integer")
                                .HasColumnName("base_def");

                            b1.Property<int>("Hp")
                                .HasColumnType("integer")
                                .HasColumnName("base_hp");

                            b1.Property<int>("Spd")
                                .HasColumnType("integer")
                                .HasColumnName("base_spd");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("OpmWiki.Domain.Entities.CharacterStats", "PvpStats", b1 =>
                        {
                            b1.Property<string>("CharacterId")
                                .HasColumnType("character varying(80)");

                            b1.Property<int>("Atk")
                                .HasColumnType("integer")
                                .HasColumnName("pvp_atk");

                            b1.Property<int>("Def")
                                .HasColumnType("integer")
                                .HasColumnName("pvp_def");

                            b1.Property<int>("Hp")
                                .HasColumnType("integer")
                                .HasColumnName("pvp_hp");

                            b1.Property<int>("Spd")
                                .HasColumnType("integer")
                                .HasColumnName("pvp_spd");

                            b1.HasKey("CharacterId");

                            b1.ToTable("characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("BaseStats")
                        .IsRequired();

                    b.Navigation("PvpStats")
                        .IsRequired();
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.CharacterEffect", b =>
                {
                    b.HasOne("OpmWiki.Domain.Entities.Character", "Character")
                        .WithMany("Effects")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.CharacterSkill", b =>
                {
                    b.HasOne("OpmWiki.Domain.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("OpmWiki.Domain.Entities.Character", b =>
                {
                    b.Navigation("Effects");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
