<script setup>
import { onMounted, ref } from 'vue'
import { createTopUp, getMyTopUps } from '../services/communityApi'
import { refreshSession } from '../services/authApi'
const requests = ref([]); const provider = ref('Bank transfer'); const referenceCode = ref(''); const amount = ref(100000); const error = ref(''); const notice = ref(''); const submitting = ref(false)
const load = async () => { try { requests.value = await getMyTopUps(); await refreshSession() } catch (e) { error.value = e.message } }
const submit = async () => { submitting.value = true; error.value = ''; notice.value = ''; try { await createTopUp({ provider: provider.value, referenceCode: referenceCode.value, amount: Number(amount.value) }); referenceCode.value = ''; notice.value = 'Đã gửi yêu cầu. Nhân viên sẽ kiểm tra và phản hồi.'; await load() } catch (e) { error.value = e.message } finally { submitting.value = false } }
const formatMoney = v => Number(v).toLocaleString('vi-VN') + 'đ'; const formatDate = v => new Date(v).toLocaleString('vi-VN')
onMounted(load)
</script>
<template><main class="min-h-screen px-4 py-16 sm:px-6 sm:py-24"><div class="mx-auto max-w-5xl"><p class="text-xs font-black uppercase tracking-[0.24em] text-opm-gold">Thanh toán</p><h1 class="mt-2 text-4xl font-black text-white">Nạp thẻ</h1><p class="mt-3 max-w-2xl text-gray-400">Gửi mã giao dịch hoặc mã tham chiếu. Không nhập mật khẩu, OTP hay toàn bộ thông tin thẻ ngân hàng.</p><div class="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><form class="h-fit space-y-4 rounded-2xl border border-white/10 bg-[#0b0d13] p-6" @submit.prevent="submit"><label class="block text-sm font-bold text-gray-400">Phương thức<select v-model="provider" class="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white"><option>Bank transfer</option><option>Momo</option><option>ZaloPay</option><option>Game card</option></select></label><label class="block text-sm font-bold text-gray-400">Mã giao dịch<input v-model="referenceCode" minlength="4" maxlength="120" required class="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-opm-gold" /></label><label class="block text-sm font-bold text-gray-400">Số tiền<input v-model.number="amount" type="number" min="10000" max="100000000" step="10000" required class="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white outline-none focus:border-opm-gold" /></label><p v-if="error" class="text-sm text-red-400">{{ error }}</p><p v-if="notice" class="text-sm text-emerald-400">{{ notice }}</p><button :disabled="submitting" class="w-full rounded-xl bg-opm-gold py-3 font-black text-black disabled:opacity-50">{{ submitting ? 'Đang gửi…' : 'Gửi yêu cầu nạp' }}</button></form><section class="rounded-2xl border border-white/10 bg-[#0b0d13] p-5"><h2 class="text-xl font-black text-white">Lịch sử yêu cầu</h2><div class="mt-4 space-y-3"><article v-for="item in requests" :key="item.id" class="rounded-xl border border-white/5 bg-black/20 p-4"><div class="flex flex-wrap justify-between gap-2"><strong class="text-white">{{ formatMoney(item.amount) }} · {{ item.provider }}</strong><span class="rounded px-2 py-1 text-xs font-black" :class="item.status === 'Approved' ? 'bg-emerald-500/10 text-emerald-300' : item.status === 'Rejected' ? 'bg-red-500/10 text-red-300' : 'bg-amber-500/10 text-amber-300'">{{ item.status }}</span></div><p class="mt-2 text-sm text-gray-400">Mã: {{ item.referenceCode }} · {{ formatDate(item.createdAt) }}</p><p v-if="item.staffNote" class="mt-2 text-sm text-gray-300">Nhân viên: {{ item.staffNote }}</p></article><p v-if="requests.length === 0" class="py-8 text-center text-gray-500">Chưa có yêu cầu nạp.</p></div></section></div></div></main></template>
